### ISSUE TITLE
Issue creating new asset volume.  Error undefined index:settings

### ISSUE THREAD

**Issue by MarcoWilliamsPF** [shennyg/azure-blob-remote-volume#1]
Copy Stacktrace Search Stackoverflow Search Google Error
PHP Notice – yii\base\ErrorException

Undefined index: settings
1. in /Users/marco/Projects/Moorage/Website/vendor/craftcms/cms/src/services/Volumes.php at line 363
354355356357358359360361362363364365366367368369370371372            $volumeRecord = $this->_getVolumeRecord($volumeUid, true);
            $isNewVolume = $volumeRecord->getIsNewRecord();
 
            $volumeRecord->name = $data['name'];
            $volumeRecord->handle = $data['handle'];
            $volumeRecord->type = $data['type'];
            $volumeRecord->hasUrls = $data['hasUrls'];
            $volumeRecord->sortOrder = $data['sortOrder'];
            $volumeRecord->url = !empty($data['url']) ? $data['url'] : null;
            $volumeRecord->settings = $data['settings'];
            $volumeRecord->uid = $volumeUid;
 
            if (!empty($data['fieldLayouts'])) {
                // Save the field layout
                $layout = FieldLayout::createFromConfig(reset($data['fieldLayouts']));
                $layout->id = $volumeRecord->fieldLayoutId;
                $layout->type = Asset::class;
                $layout->uid = key($data['fieldLayouts']);
                Craft::$app->getFields()->saveLayout($layout);
2. in /Users/marco/Projects/Moorage/Website/vendor/craftcms/cms/src/web/ErrorHandler.php at line 81 – yii\base\ErrorHandler::handleError(8, 'Undefined index: settings', '/Users/marco/Projects/Moorage/We...', 363)

**Comment by Brian-C-Noble** [comment]
This error occurred when re-saving a section that has an asset field connected to an Azure Volumn 
RuntimeException: 
The provided account key '' is not a valid base64 string. It has to pass the check 'base64_decode(<user_account_key>, true)'. in C:\wamp64\www\gelsons\vendor\microsoft\azure-storage-common\src\Common\Internal\StorageServiceSettings.php:112

Stack trace:
```#0 C:\wamp64\www\gelsons\vendor\microsoft\azure-storage-common\src\Common\Internal\ServiceSettings.php(133): MicrosoftAzure\Storage\Common\Internal\StorageServiceSettings::MicrosoftAzure\Storage\Common\Internal\{closure}('')
#1 C:\wamp64\www\gelsons\vendor\microsoft\azure-storage-common\src\Common\Internal\ServiceSettings.php(273): MicrosoftAzure\Storage\Common\Internal\ServiceSettings::MicrosoftAzure\Storage\Common\Internal\{closure}(Array)
#2 C:\wamp64\www\gelsons\vendor\microsoft\azure-storage-common\src\Common\Internal\StorageServiceSettings.php(399): MicrosoftAzure\Storage\Common\Internal\ServiceSettings::matchedSpecification(Array, Object(Closure), Object(Closure))
#3 C:\wamp64\www\gelsons\vendor\microsoft\azure-storage-blob\src\Blob\BlobRestProxy.php(134): MicrosoftAzure\Storage\Common\Internal\StorageServiceSettings::createFromConnectionString('DefaultEndpoint...')
#4 C:\wamp64\www\gelsons\vendor\shennyg\azure-blob-remote-volume\src\AzureVolume.php(53): MicrosoftAzure\Storage\Blob\BlobRestProxy::createBlobService('DefaultEndpoint...')
#5 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\base\FlysystemVolume.php(307): shennyg\azureblobremotevolume\AzureVolume->createAdapter()
#6 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\base\FlysystemVolume.php(319): craft\base\FlysystemVolume->adapter()
#7 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\base\FlysystemVolume.php(48): craft\base\FlysystemVolume->filesystem()
#8 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\services\Assets.php(757): craft\base\FlysystemVolume->getFileList('pages/', false)
#9 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\validators\AssetLocationValidator.php(132): craft\services\Assets->getNameReplacementInFolder('shopping.jpg', 21)
#10 C:\wamp64\www\gelsons\vendor\yiisoft\yii2\validators\Validator.php(267): craft\validators\AssetLocationValidator->validateAttribute(Object(craft\elements\Asset), 'newLocation')
#11 C:\wamp64\www\gelsons\vendor\yiisoft\yii2\base\Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Asset), Array)
#12 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\services\Elements.php(412): yii\base\Model->validate()
#13 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\services\Assets.php(187): craft\services\Elements->saveElement(Object(craft\elements\Asset))
#14 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\fields\Assets.php(429): craft\services\Assets->moveAsset(Object(craft\elements\Asset), Object(craft\models\VolumeFolder))
#15 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\base\Element.php(1841): craft\fields\Assets->afterElementSave(Object(craft\elements\Entry), false)
#16 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\elements\Entry.php(1080): craft\base\Element->afterSave(false)
#17 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\services\Elements.php(498): craft\elements\Entry->afterSave(false)
#18 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\services\Sections.php(1299): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#19 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\services\Sections.php(635): craft\services\Sections->_onSaveSingle(Object(craft\models\Section), false, Array)
#20 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\controllers\SectionsController.php(186): craft\services\Sections->saveSection(Object(craft\models\Section))
#21 [internal function]: craft\controllers\SectionsController->actionSaveSection()
#22 C:\wamp64\www\gelsons\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#23 C:\wamp64\www\gelsons\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\web\Controller.php(104): yii\base\Controller->runAction('save-section', Array)
#25 C:\wamp64\www\gelsons\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('save-section', Array)
#26 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\web\Application.php(282): yii\base\Module->runAction('sections/save-s...', Array)
#27 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\web\Application.php(542): craft\web\Application->runAction('sections/save-s...', Array)
#28 C:\wamp64\www\gelsons\vendor\craftcms\cms\src\web\Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#29 C:\wamp64\www\gelsons\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 C:\wamp64\www\gelsons\web\index.php(21): yii\base\Application->run()
#31 {main}
